site_name: iRODS Docs
repo_url: https://github.com/irods/irods_docs
site_description: Open Source Data Management
site_author: iRODS Consortium
site_dir: site
docs_dir: docs
google_analytics:
 - UA-49704995-1
 - auto
theme: readthedocs
extra_css:
 - irods.css
extra_javascript:
 - irods.js

markdown_extensions:
 - admonition
 - attr_list
 - def_list


pages:
 - Home: 'index.md'
 - Why iRODS?: 'why_irods.md'
 - Release Notes: 'release_notes.md'
 - Getting Started:
    - Download: 'getting_started/download.md'
    - Installation: 'getting_started/installation.md'
    - Upgrading: 'getting_started/upgrading.md'
 - Plugins:
    - Plugin Interfaces: 'plugins/plugin_interfaces.md'
    - Pluggable Microservices: 'plugins/pluggable_microservices.md'
    - Composable Resources: 'plugins/composable_resources.md'
    - Pluggable Authentication: 'plugins/pluggable_authentication.md'
    - Pluggable Network: 'plugins/pluggable_network.md'
    - Pluggable Database: 'plugins/pluggable_database.md'
    - Pluggable RPC API: 'plugins/pluggable_rpc_api.md'
    - Pluggable Rule Engine: 'plugins/pluggable_rule_engine.md'
    - Dynamic Policy Enforcement Points: 'plugins/dynamic_policy_enforcement_points.md'
    - iRODS Rule Language: 'plugins/irods_rule_language.md'
 - System Overview:
    - Process Model: 'system_overview/process_model.md'
    - Control Plane: 'system_overview/control_plane.md'
    - Configuration: 'system_overview/configuration.md'
    - SSL: 'system_overview/ssl.md'
    - Users and Permissions: 'system_overview/users_and_permissions.md'
    - Backing Up: 'system_overview/backing_up.md'
    - Federation: 'system_overview/federation.md'
    - Distributing iCommands: 'system_overview/distributing_icommands.md'
    - Glossary: 'system_overview/glossary.md'
    - Best Practices: 'system_overview/best_practices.md'
    - Troubleshooting: 'system_overview/troubleshooting.md'
    - Tips and Tricks: 'system_overview/tips_and_tricks.md'
 - iCommands:
    - Administrator: 'icommands/administrator.md'
    - User: 'icommands/user.md'
    - Metadata: 'icommands/metadata.md'
    - Tickets: 'icommands/tickets.md'
    - Groupadmin: 'icommands/groupadmin.md'
 - Doxygen: 'doxygen/index.html'
 - Developers:
    - Contributing: 'developers/contributing.md'
    - Development Tools: 'developers/development_tools.md'
 - Legacy Release Notes: 'legacy_release_notes.md'

